name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        ros: [melodic, noetic]

    name: ${{ matrix.ros }}
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: ${{ matrix.ros }}
    steps:
      - uses: actions/checkout@v3

      - name: industrial_ci
        uses: ros-industrial/industrial_ci@master
